"""Add notifications table

Revision ID: 0a049c34c775
Revises: 7d6f0401b0c6
Create Date: 2025-09-16 10:49:19.397621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a049c34c775'
down_revision = '7d6f0401b0c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('related_contract_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['related_contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_recipient_id'), ['recipient_id'], unique=False)

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_user_id'))
        batch_op.drop_index(batch_op.f('uix_contract_number_deleted_at'))
        batch_op.drop_column('focal_person_a_name')
        batch_op.drop_column('focal_person_a_email')
        batch_op.drop_column('party_a_position')
        batch_op.drop_column('party_a_name')
        batch_op.drop_column('focal_person_a_phone')
        batch_op.drop_column('party_a_address')
        batch_op.drop_column('focal_person_a_position')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('focal_person_a_position', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('party_a_address', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('focal_person_a_phone', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('party_a_name', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('party_a_position', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('focal_person_a_email', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('focal_person_a_name', mysql.VARCHAR(length=100), nullable=True))
        batch_op.create_index(batch_op.f('uix_contract_number_deleted_at'), ['contract_number', 'deleted_at'], unique=True)
        batch_op.create_index(batch_op.f('ix_contracts_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_creator_id'))

    op.drop_table('notifications')
    # ### end Alembic commands ###
