"""Add contracts table

Revision ID: 0d18d73db5ed
Revises: dcd5f4c08784
Create Date: 2025-08-21 11:50:05.790297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d18d73db5ed'
down_revision = 'dcd5f4c08784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_title', sa.String(length=255), nullable=False),
    sa.Column('contract_number', sa.String(length=50), nullable=False),
    sa.Column('organization_name', sa.String(length=100), nullable=True),
    sa.Column('party_a_name', sa.String(length=100), nullable=True),
    sa.Column('party_a_position', sa.String(length=100), nullable=True),
    sa.Column('party_a_address', sa.Text(), nullable=True),
    sa.Column('party_b_full_name_with_title', sa.String(length=255), nullable=True),
    sa.Column('party_b_address', sa.Text(), nullable=True),
    sa.Column('party_b_phone', sa.String(length=20), nullable=True),
    sa.Column('party_b_email', sa.String(length=100), nullable=True),
    sa.Column('registration_number', sa.String(length=50), nullable=True),
    sa.Column('registration_date', sa.String(length=50), nullable=True),
    sa.Column('agreement_start_date', sa.String(length=50), nullable=True),
    sa.Column('agreement_end_date', sa.String(length=50), nullable=True),
    sa.Column('total_fee_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('gross_amount_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('payment_installment_desc', sa.String(length=255), nullable=True),
    sa.Column('payment_gross', sa.String(length=50), nullable=True),
    sa.Column('payment_net', sa.String(length=50), nullable=True),
    sa.Column('workshop_description', sa.String(length=255), nullable=True),
    sa.Column('focal_person_a_name', sa.String(length=100), nullable=True),
    sa.Column('focal_person_a_position', sa.String(length=100), nullable=True),
    sa.Column('focal_person_a_phone', sa.String(length=20), nullable=True),
    sa.Column('focal_person_a_email', sa.String(length=100), nullable=True),
    sa.Column('party_a_signature_name', sa.String(length=100), nullable=True),
    sa.Column('party_b_signature_name', sa.String(length=100), nullable=True),
    sa.Column('party_b_position', sa.String(length=100), nullable=True),
    sa.Column('total_fee_words', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('deliverables', sa.Text(), nullable=True),
    sa.Column('output_description', sa.Text(), nullable=True),
    sa.Column('custom_article_sentences', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contracts')
    # ### end Alembic commands ###
