"""Add vat_organization_name to Contract table

Revision ID: 47e7bb1d827c
Revises: 0a049c34c775
Create Date: 2025-09-30 14:21:57.411565

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '47e7bb1d827c'
down_revision = '0a049c34c775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vat_organization_name', sa.String(length=255), nullable=True))
        batch_op.drop_index(batch_op.f('ix_contracts_user_id'))
        batch_op.drop_index(batch_op.f('uix_contract_number_deleted_at'))
        batch_op.drop_column('party_a_name')
        batch_op.drop_column('focal_person_a_phone')
        batch_op.drop_column('party_a_address')
        batch_op.drop_column('focal_person_a_email')
        batch_op.drop_column('focal_person_a_name')
        batch_op.drop_column('focal_person_a_position')
        batch_op.drop_column('party_a_position')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('party_a_position', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('focal_person_a_position', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('focal_person_a_name', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('focal_person_a_email', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('party_a_address', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('focal_person_a_phone', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('party_a_name', mysql.VARCHAR(length=100), nullable=True))
        batch_op.create_index(batch_op.f('uix_contract_number_deleted_at'), ['contract_number', 'deleted_at'], unique=True)
        batch_op.create_index(batch_op.f('ix_contracts_user_id'), ['user_id'], unique=False)
        batch_op.drop_column('vat_organization_name')

    # ### end Alembic commands ###
