"""add uploaded_intern table

Revision ID: 5516e82be46a
Revises: 8c2f2ab4f4a5
Create Date: 2025-11-10 09:04:50.128153

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5516e82be46a'
down_revision = '8c2f2ab4f4a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_intern',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uploaded_intern', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploaded_intern_uploaded_at'), ['uploaded_at'], unique=False)

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_user_id'))
        batch_op.drop_index(batch_op.f('uix_contract_number_deleted_at'))
        batch_op.drop_column('registration_number')
        batch_op.drop_column('registration_date')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['contract_no'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_date', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('registration_number', mysql.VARCHAR(length=50), nullable=True))
        batch_op.create_index(batch_op.f('uix_contract_number_deleted_at'), ['contract_number', 'deleted_at'], unique=True)
        batch_op.create_index(batch_op.f('ix_contracts_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('uploaded_intern', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploaded_intern_uploaded_at'))

    op.drop_table('uploaded_intern')
    # ### end Alembic commands ###
