"""check schema sytnc

Revision ID: 64e74c3b2e44
Revises: 64fdf7390a4f
Create Date: 2025-10-22 15:10:35.325829

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '64e74c3b2e44'
down_revision = '64fdf7390a4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_user_id'))
        batch_op.drop_index(batch_op.f('uix_contract_number_deleted_at'))
        batch_op.drop_column('registration_date')
        batch_op.drop_column('registration_number')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['contract_no'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_number', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('registration_date', mysql.VARCHAR(length=50), nullable=True))
        batch_op.create_index(batch_op.f('uix_contract_number_deleted_at'), ['contract_number', 'deleted_at'], unique=True)
        batch_op.create_index(batch_op.f('ix_contracts_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###
