"""Add deduct_tax_code to contracts table

Revision ID: 7d6f0401b0c6
Revises: 4b626fbe878b
Create Date: 2025-09-15 09:13:48.644560

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7d6f0401b0c6'
down_revision = '4b626fbe878b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deduct_tax_code', sa.String(length=50), nullable=True))
        batch_op.drop_index(batch_op.f('ix_contracts_user_id'))
        batch_op.drop_index(batch_op.f('uix_contract_number_deleted_at'))
        batch_op.drop_column('focal_person_a_phone')
        batch_op.drop_column('party_a_address')
        batch_op.drop_column('focal_person_a_email')
        batch_op.drop_column('focal_person_a_position')
        batch_op.drop_column('party_a_name')
        batch_op.drop_column('party_a_position')
        batch_op.drop_column('focal_person_a_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('focal_person_a_name', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('party_a_position', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('party_a_name', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('focal_person_a_position', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('focal_person_a_email', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('party_a_address', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('focal_person_a_phone', mysql.VARCHAR(length=20), nullable=True))
        batch_op.create_index(batch_op.f('uix_contract_number_deleted_at'), ['contract_number', 'deleted_at'], unique=True)
        batch_op.create_index(batch_op.f('ix_contracts_user_id'), ['user_id'], unique=False)
        batch_op.drop_column('deduct_tax_code')

    # ### end Alembic commands ###
