"""Add unique constraint to phone_number in user table

Revision ID: 903d0fec9bf3
Revises: 715773f345d4
Create Date: 2025-09-08 15:59:24.746273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '903d0fec9bf3'
down_revision = '715773f345d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['phone_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
