"""Add payment_installments column to contracts table

Revision ID: a4b214b336cd
Revises: 04187d146d5a
Create Date: 2025-08-28 09:30:00.595559

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a4b214b336cd'
down_revision = '04187d146d5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_installments', sa.JSON(), nullable=True))
        batch_op.drop_column('payment_installment_desc')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_installment_desc', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('payment_installments')

    # ### end Alembic commands ###
