"""Add employees table

Revision ID: b2ce0fad50ba
Revises: d7fae136764b
Create Date: 2025-10-22 13:57:17.577177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b2ce0fad50ba'
down_revision = 'd7fae136764b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contract_no', sa.String(length=50), nullable=False),
    sa.Column('contract_type', sa.String(length=100), nullable=False),
    sa.Column('organization_name', sa.String(length=255), nullable=True),
    sa.Column('representative_name', sa.String(length=100), nullable=True),
    sa.Column('representative_title', sa.String(length=100), nullable=True),
    sa.Column('organization_address', sa.Text(), nullable=True),
    sa.Column('organization_tel', sa.String(length=50), nullable=True),
    sa.Column('organization_fax', sa.String(length=50), nullable=True),
    sa.Column('organization_email', sa.String(length=150), nullable=True),
    sa.Column('employee_name', sa.String(length=255), nullable=False),
    sa.Column('employee_address', sa.Text(), nullable=True),
    sa.Column('employee_tel', sa.String(length=50), nullable=True),
    sa.Column('employee_email', sa.String(length=150), nullable=True),
    sa.Column('position_title', sa.String(length=150), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('working_hours', sa.String(length=255), nullable=True),
    sa.Column('salary_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('salary_grade', sa.String(length=50), nullable=True),
    sa.Column('salary_amount_words', sa.String(length=255), nullable=True),
    sa.Column('medical_allowance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('child_education_allowance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('delivery_benefit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('delivery_benefit_miscarriage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('death_benefit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('severance_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('thirteenth_month_salary', sa.Boolean(), nullable=True),
    sa.Column('employer_signature_name', sa.String(length=150), nullable=True),
    sa.Column('employee_signature_name', sa.String(length=150), nullable=True),
    sa.Column('employer_signature_date', sa.Date(), nullable=True),
    sa.Column('employee_signature_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_user_id'))
        batch_op.drop_index(batch_op.f('uix_contract_number_deleted_at'))
        batch_op.drop_column('registration_number')
        batch_op.drop_column('registration_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_date', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('registration_number', mysql.VARCHAR(length=50), nullable=True))
        batch_op.create_index(batch_op.f('uix_contract_number_deleted_at'), ['contract_number', 'deleted_at'], unique=True)
        batch_op.create_index(batch_op.f('ix_contracts_user_id'), ['user_id'], unique=False)

    op.drop_table('employees')
    # ### end Alembic commands ###
