""" Check schema update employees

Revision ID: d0dcabefe2ee
Revises: 5516e82be46a
Create Date: 2025-11-26 08:13:00.602825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd0dcabefe2ee'
down_revision = '5516e82be46a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_user_id'))
        batch_op.drop_index(batch_op.f('uix_contract_number_deleted_at'))
        batch_op.drop_column('registration_number')
        batch_op.drop_column('registration_date')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('salary_amount_words',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['contract_no'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('salary_amount_words',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_date', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('registration_number', mysql.VARCHAR(length=50), nullable=True))
        batch_op.create_index(batch_op.f('uix_contract_number_deleted_at'), ['contract_number', 'deleted_at'], unique=True)
        batch_op.create_index(batch_op.f('ix_contracts_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###
