"""Add interns table

Revision ID: d7fae136764b
Revises: 47e7bb1d827c
Create Date: 2025-10-20 10:36:40.265293

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd7fae136764b'
down_revision = '47e7bb1d827c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contract_id', sa.String(length=50), nullable=False),
    sa.Column('intern_title', sa.String(length=10), nullable=True),
    sa.Column('intern_name', sa.String(length=255), nullable=False),
    sa.Column('intern_role', sa.String(length=255), nullable=False),
    sa.Column('intern_address', sa.Text(), nullable=True),
    sa.Column('intern_phone', sa.String(length=20), nullable=True),
    sa.Column('intern_email', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('duration', sa.String(length=50), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('working_hours', sa.String(length=100), nullable=True),
    sa.Column('allowance_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('has_nssf', sa.Boolean(), nullable=True),
    sa.Column('supervisor_info', sa.JSON(), nullable=True),
    sa.Column('job_description_file', sa.String(length=255), nullable=True),
    sa.Column('employer_representative_name', sa.String(length=100), nullable=True),
    sa.Column('employer_representative_title', sa.String(length=100), nullable=True),
    sa.Column('employer_address', sa.Text(), nullable=True),
    sa.Column('employer_phone', sa.String(length=20), nullable=True),
    sa.Column('employer_fax', sa.String(length=20), nullable=True),
    sa.Column('employer_email', sa.String(length=100), nullable=True),
    sa.Column('intern_signature_date', sa.Date(), nullable=True),
    sa.Column('employer_signature_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id')
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_user_id'))
        batch_op.drop_index(batch_op.f('uix_contract_number_deleted_at'))
        batch_op.drop_column('focal_person_a_email')
        batch_op.drop_column('focal_person_a_name')
        batch_op.drop_column('party_a_position')
        batch_op.drop_column('registration_number')
        batch_op.drop_column('party_a_address')
        batch_op.drop_column('party_a_name')
        batch_op.drop_column('registration_date')
        batch_op.drop_column('focal_person_a_phone')
        batch_op.drop_column('organization_name')
        batch_op.drop_column('focal_person_a_position')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('focal_person_a_position', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('organization_name', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('focal_person_a_phone', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('registration_date', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('party_a_name', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('party_a_address', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('registration_number', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('party_a_position', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('focal_person_a_name', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('focal_person_a_email', mysql.VARCHAR(length=100), nullable=True))
        batch_op.create_index(batch_op.f('uix_contract_number_deleted_at'), ['contract_number', 'deleted_at'], unique=True)
        batch_op.create_index(batch_op.f('ix_contracts_user_id'), ['user_id'], unique=False)

    op.drop_table('interns')
    # ### end Alembic commands ###
