"""Add role_id and department_id to user

Revision ID: dcd5f4c08784
Revises: 02d3ec694225
Create Date: 2025-08-21 08:15:46.450893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcd5f4c08784'
down_revision = '02d3ec694225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_role_id'), ['role_id'], unique=False)
        batch_op.create_foreign_key(None, 'department', ['department_id'], ['id'])
        batch_op.create_foreign_key(None, 'role', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_user_role_id'))
        batch_op.drop_index(batch_op.f('ix_user_department_id'))
        batch_op.drop_column('department_id')
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###
